apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-esoraya1995-app
  labels:
    app: student-esoraya1995-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-esoraya1995-app
  template:
    metadata:
      labels:
        app: student-esoraya1995-app
    spec:
      containers:
        - name: student-esoraya1995-app
          image: ${IMAGE}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
